resources:
- name: peters-pipelines
  type: git
  source:
    uri: https://github.com/sharadg/peters-pipelines.git
- name: pks-prometheus
  type: git
  source:
    uri: https://github.com/Oskoss/pks-prometheus.git

jobs:
- name: setup-prometheus
  plan:
  - get: peters-pipelines
  - get: pks-prometheus
  - task: authenticate-kubernetes
    file: peters-pipelines/kubernetes/tasks/authenticate-kubernetes/task.yml
    params:
      PKS_API_URL: {{pks_api_url}}
      PKS_API_USERNAME: {{pks_api_username}}
      PKS_API_PASSWORD: {{pks_api_password}}
      PKS_CLUSTER_NAME: {{pks_cluster_name}}
      PKS_CONVERT_HOST_TO_IP: {{pks_convert_host_to_ip}}
  - task: create-namespace
    file: peters-pipelines/kubernetes/tasks/create-namespace/task.yml
    params:
      K8S_NAMESPACE: {{k8s_namespace}}
  - task: create-cluster-role
    file: peters-pipelines/kubernetes/tasks/create-prometheus-cluster-user/task.yml
    params:
      K8S_NAMESPACE: {{k8s_namespace}}
  - task: create-config-map
    file: peters-pipelines/kubernetes/tasks/create-prometheus-config-map/task.yml
    params:
      K8S_NAMESPACE: {{k8s_namespace}}
  - task: create-deployment
    file: peters-pipelines/kubernetes/tasks/create-prometheus-deployment/task.yml
    params:
      K8S_NAMESPACE: {{k8s_namespace}}
#  - task: create-loadbalancer
#    file: peters-pipelines/kubernetes/tasks/create-prometheus-loadbalancer/task.yml
#    params:
#      K8S_NAMESPACE: {{k8s_namespace}}
  
